dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.opengauss.Driver
    jdbcUrl: jdbc:opengauss://127.0.0.1:15432/test?batchMode=on
    username: gaussdb
    password: Enmo@123
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.opengauss.Driver
    jdbcUrl: jdbc:opengauss://127.0.0.1:15433/test?batchMode=on
    username: gaussdb
    password: Enmo@123

rules:
- !SHARDING
  defaultDatabaseStrategy:
    none: null
  defaultTableStrategy:
    none: null
  shardingAlgorithms:
    ds_count_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${id % 2}
    t_account_inline:
      type: INLINE
      props:
        algorithm-expression: account_${transaction_id % 2}
  tables:
    account:
      actualDataNodes: ds_${0..1}.account_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds_count_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: transaction_id
          shardingAlgorithmName: t_account_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123

- !TRANSACTION
  defaultType: XA
  providerType: Narayana

props:
  sql-show: false
